module.exports = {
  theme: {
    extend: {
      colors: {
        white: '#ffffff',
        normal: '#A8A878',
        fighting: '#C03028',
        flying: '#A890F0',
        poison: '#A040A0',
        ground: '#E0C068',
        rock: '#B8A038',
        bug: '#A8B820',
        ghost: '#705898',
        steel: '#B8B8D0',
        fire: '#FA6C6C',
        water: '#6890F0',
        grass: '#48CFB2',
        electric: '#FFCE4B',
        psychic: '#F85888',
        ice: '#98D8D8',
        dragon: '#7038F8',
        dark: '#705848',
        fairy: '#EE99AC',

        hp: '#ff0000',
        hp_fade: '#ff5959',
        attack: '#f08030',
        attack_fade: '#f5ac78',
        defense: '#f8d030',
        defense_fade: '#fae078',
        sp_atk: '#6890f0',
        sp_atk_fade: '#9db7f5',
        sp_def: '#78c850',
        sp_def_fade: '#a7db8d',
        speed: '#f85888',
        speed_fade: '#fa92b2',
      },
    },
  },
  variants: {},
  plugins: [],
  purge: {
    content: [
      `components/**/*.{vue,js}`,
      `layouts/**/*.vue`,
      `pages/**/*.vue`,
      `plugins/**/*.{js,ts}`,
      `nuxt.config.{js,ts}`,
    ],
    options: {
      safelist: [/^bg-/, /^text-/, /^border-/],
    },
  },
};
